import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  //  Docusaurus 默认会生成一个由 docs 文件夹下面的文件去构建
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // 也可以手动的生成一个侧边栏
  
  // tutorialSidebar: [
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['hello','my','little'],
  //   },
  // ],
  
};

export default sidebars;
