name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # 关键修复：确保 docusaurus 可执行
      - name: Fix permissions for docusaurus
        run: chmod +x node_modules/.bin/docusaurus

      - name: Build project
        run: |
          echo "开始构建项目..."
          npm run build
          echo "构建完成！"
      - name: Debug build folder
        run: |
          echo "Build 目录内容："
          ls -la build
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 22 ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
      - name: Deploy build folder to server
        run: |
          echo "开始部署到服务器..."
          rsync -avz -e "ssh -p 22" ./build/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/www/wwwroot/www.yelv.site/
          echo "文件已传输！"

    # 9. 重启服务器上的 Nginx 服务（如果需要）
      - name: Restart nginx on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo chown -R www:www /www/wwwroot/www.yelv.site/blogweb
            sudo systemctl restart nginx
