name: Deploy to Baota

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 步骤 1：检出代码
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      # 步骤 2：设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 步骤 3：安装依赖
      - name: Install dependencies
        run: npm install

      # 步骤 4：设置权限并构建项目
      - name: Build project
        run: |
          chmod +x node_modules/.bin/docusaurus
          npm run build

      # 步骤 5：调试工作目录
      - name: Debug workspace
        run: |
          echo "Workspace contents:"
          ls -la $GITHUB_WORKSPACE
          echo "Build directory contents:"
          ls -la $GITHUB_WORKSPACE/build

      # 步骤 6：同步 build 文件夹到服务器
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd $GITHUB_WORKSPACE
            rsync -avz --delete --exclude='.user.ini' -e "ssh -o StrictHostKeyChecking=no" build/ /www/wwwroot/www.yelv.site/
            sudo chown -R www:www /www/wwwroot/www.yelv.site
            sudo systemctl restart nginx
