name: Deploy to Baota

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 步骤 1：检出代码（包含本地 build 文件夹）
      - name: Checkout code
        uses: actions/checkout@v3

      # 步骤 2：安全同步 build 文件夹到服务器（保留 .user.ini）
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 使用 rsync 同步并排除 .user.ini
            rsync -avz --delete --exclude='.user.ini' -e "ssh -o StrictHostKeyChecking=no" ./build/ root@${{ secrets.SERVER_IP }}:/www/wwwroot/www.yelv.site/build/

            # 设置目录权限（www 用户组是宝塔面板的默认用户组）
            sudo chown -R www:www /www/wwwroot/www.yelv.site/build

            # 重启 Nginx 确保更新生效
            sudo systemctl restart nginx
