name: Deploy to Baota

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 步骤 1：检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 步骤 2：安装 Node.js（使用官方推荐语法）
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0' # 使用字符串格式确保版本号解析正确
          cache: pnpm
          check-latest: true # 强制检查最新可用版本

      # 步骤 3：验证 Node.js 和 npm
      - name: Check Node.js and npm
        run: |
          node -v
          npm -v

      # 步骤 4：直接安装 pnpm（绕过 Corepack）
      - name: Install pnpm
        run: npm install -g pnpm

      # 步骤 5：验证 pnpm
      - name: Check pnpm
        run: pnpm -v

      # 步骤 6：安装依赖并构建
      - name: Install and Build
        run: |
          pnpm install
          pnpm build

      # 步骤 7：部署到服务器
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /www/wwwroot/www.yelv.site/build
            find . -maxdepth 1 ! -name '.user.ini' -exec rm -rf {} +
            rsync -avz --delete ${{ github.workspace }}/build/ root@${{ secrets.SERVER_IP }}:/www/wwwroot/www.yelv.site/build/
            chown -R www:www /www/wwwroot/www.yelv.site/build
            chmod -R 755 /www/wwwroot/www.yelv.site/build
            systemctl restart nginx
