name: Deploy to Server

on:
  push:
    branches:
      - main # 或其他分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      # 2. 安装 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. 安装依赖
      - name: Install dependencies
        run: npm install

      # 4. 强制执行构建
      - name: Build project
        run: |
          echo "开始构建项目..."
          npm run build
          echo "构建完成！"

      # 5. 查看 build 文件夹内容（可选，调试用）
      - name: Debug build folder
        run: |
          echo "Build 目录内容："
          ls -la build

      # 6. 启动 ssh-agent 并添加 key
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 7. 添加服务器到 known_hosts（避免首次连接警告）
      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 22 ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      # 8. 使用 rsync 部署 build 文件夹
      - name: Deploy build folder to server
        run: |
          echo "开始部署到服务器..."
          rsync -avz -e "ssh -p 22" ./build/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/www/wwwroot/www.yelv.site/
          echo "文件已传输！"

      # 9. 重启服务器上的 Nginx 服务（如果需要）
      - name: Restart nginx on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo chown -R www:www /www/wwwroot/www.yelv.site
            sudo systemctl restart nginx
