name: Deploy to Baota

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 步骤 1：检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 步骤 2：安装 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0' # 确保版本号正确
          cache: pnpm
          check-latest: true

      # 步骤 3：安装 pnpm 并显式更新 PATH
      - name: Install pnpm
        run: |
          npm install -g pnpm --prefix=/usr/local  # 指定全局安装路径
          echo "::add-path::/usr/local/bin"        # 手动添加路径到 PATH

      # 步骤 4：验证环境
      - name: Check Environment
        run: |
          echo "PATH: $PATH"
          pnpm -v

      # 步骤 5：安装依赖并构建
      - name: Install and Build
        run: |
          pnpm install
          pnpm build

      # 步骤 6：部署到服务器
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
