name: Deploy to Baota

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 步骤 1：检出代码（包含本地 build 文件夹）
      - name: Checkout code
        uses: actions/checkout@v3

      # 步骤 2：直接同步 build 文件夹到服务器
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 删除服务器旧文件（保留宝塔自动生成的 .user.ini）
            cd /www/wwwroot/www.yelv.site/build
            find . -maxdepth 1 ! -name '.user.ini' -exec rm -rf {} +

            # 同步本地 build 文件夹内容到服务器
            rsync -avz --delete ${{ github.workspace }}/build/ root@${{ secrets.SERVER_IP }}:/www/wwwroot/www.yelv.site/build/

            # 修复权限（宝塔默认用户组为 www）
            chown -R www:www /www/wwwroot/www.yelv.site/build
            chmod -R 755 /www/wwwroot/www.yelv.site/build

            # 重启 Nginx 生效（可选）
            systemctl restart nginx