name: Deploy to Baota

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate build directory
        run: |
          echo "当前工作目录: $PWD"
          ls -la
          echo "检查 build 目录:"
          ls -la build/

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "===== 开始部署 ====="
            echo "检查服务器目标目录:"
            ls -la /www/wwwroot/www.yelv.site/build/

            echo "执行同步操作:"
            rsync -avz --progress --delete --exclude='.user.ini' -e "ssh -o StrictHostKeyChecking=no" ./build/ root@${{ secrets.SERVER_IP }}:/www/wwwroot/www.yelv.site/build/

            echo "验证同步结果:"
            ls -la /www/wwwroot/www.yelv.site/build/

            sudo chown -R www:www /www/wwwroot/www.yelv.site/build
            sudo systemctl restart nginx
